name: aom
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  #- _libgcc_mutex=0.1
  #- absl-py=0.9.0
  - attrs=20.2.0
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  #- c-ares=1.15.0
  #- ca-certificates=2020.10.14
  - cachetools=4.1.1
  - certifi=2020.6.20
  #- cffi=1.14.2
  - chardet=3.0.4
  - click=7.1.2
  #- cryptography=3.0
  #- cudatoolkit=10.1.243
  #- cudatoolkit-dev=10.1.243
  #- cxxfilt=0.2.2
  #- freetype=2.10.2
  - google-auth=1.20.1
  - google-auth-oauthlib=0.4.1
  #- grpcio=1.31.0
  - idna=2.10
  - importlib-metadata=1.7.0
  - iniconfig=1.0.1
  #- intel-openmp=2020.1
  #- jpeg=9b
  #- lcms2=2.11
  #- ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  #- libgcc=7.2.0
  #- libgcc-ng=9.1.0
  - libpng=1.6.37
  #- libprotobuf=3.12.4
  #- libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - lz4-c=1.9.2
  - markdown=3.2.2
  #- mkl=2020.1
  #- mkl-service=2.3.0
  #- mkl_fft=1.1.0
  #- mkl_random=1.1.1
  - more-itertools=8.5.0
  - ncurses=6.2
  #- ninja=1.10.0
  - numpy=1.19.5
  - numpy-base=1.19.5
  #- nvidia-apex=0.1
  - oauthlib=3.1.0
  - olefile=0.46
  - openssl=1.1.1h
  - packaging=20.4
  - pip=20.1.1
  - pluggy=0.13.1
  #- protobuf=3.12.4
  - py=1.9.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pyjwt=1.7.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - pytest=6.1.1
  - python=3.8
  - python_abi=3.8
  - pytorch
  - pyyaml=5.3.1
  #- readline=8.0
  - requests=2.24.0
  - requests-oauthlib=1.3.0
  - rsa=4.6
  #- setuptools=49.2.0
  - six=1.15.0
  #- sqlite=3.32.3
  - tensorboard=2.2.1
  - tensorboard-plugin-wit=1.6.0
  - tk=8.6.10
  - toml=0.10.1
  - torchvision
  - urllib3=1.25.10
  - werkzeug=1.0.1
  #- wheel=0.34.2
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.1.0
  #- zlib=1.2.11
  - zstd=1.4.5
  - pip:
#     - cloudpickle==1.6.0
#     - cycler==0.10.0
#     - cython==0.29.21
#     - filelock==3.0.12
#     - future==0.18.2
#     - fvcore==0.1.1.post20200716
#     - joblib==0.16.0
#     - kiwisolver==1.2.0
#     - matplotlib==3.3.1
#     - mock==4.0.2
#     - nvidia-ml-py3==7.352.0
#     - opencv-python==4.4.0.42
#     - pillow==6.2.2
#     - portalocker==2.0.0
#     - progressbar2==3.53.1
#     - pycocotools==2.0.2
#     - pydot==1.4.1
#     - python-dateutil==2.8.1
#     - python-utils==2.4.0
#     - regex==2020.7.14
#     - sacremoses==0.0.43
#     - sentencepiece==0.1.91
#     - tabulate==0.8.7
#     - termcolor==1.1.0
    - tokenizers
#     - tqdm==4.48.2
#     - transformers==3.0.2
#     - visual-genome==1.1.1
#     - yacs==0.1.8

-------
python=3.8.20
pytorch
transformers=3.0.2
conda install conda-forge::spacy=2.3.7
python -m spacy download en_core_web_sm
pip install rich
pip install pytorch_transformers